//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 王超FishJoy
//  @ File Name : StaticData.cpp
//  @ Date : 2017/9/27
//  @ Author : KrisChao
//
//


#include "StaticData.h"

StaticData * StaticData::sharedStaticData() {

    static StaticData* g_sharedStaticData=NULL;
}

void StaticData::purge() {

    CC_SAFE_RELEASE_NULL(g_sharedStaticData);
}

int StaticData::intValueForKey(const std::string &key) {

    return _dictionary->valueForKey(key)->intValue();
}

const char * StaticData::stringValueFromKey(std::string &key) {

    return _dictionary->valueForKey(key)->getCString();
}

float StaticData::floatValueFromKey(const std::string &key) {

    return _dictionary->valueForKey(key)->floatValue();
}

boolean StaticData::booleanFromKey(const std::string &key) {

    return _dictionary->valueForKey(key)->boolValue();
}

cocos2d::CCPoint StaticData::pointFromKey(const std::string &key) {

    return CCPointFromString(_dictionary->valueForKey(key)->getCString());
}

cocos2d::CCRect StaticData::rectFromKey(const std::string &key) {

    return CCRectFromString(_dictionary->valueForKey(key)->getCString());
}

cocos2d::CCSize StaticData::sizeFormKey(const std::string &key) {

    return CCSizeFromString(_dictionary->valueForKey(key)->getCString());
}

bool StaticData::init() {
    _dictionary = CCDictionary::createWithContensOfFile(_staticFileName.c_str());
    _dictionary->retain();

    return true;
}

StaticData::StaticData() {

}

StaticData::~StaticData() {
  CC_SAFE_RELEASE_NULL(_dictionary);
/*
	if(NULL != _dictionary)
	{
		_dictionary->release();
		_dictionary = NULL;
	}*/
}
