n//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : 王超_fishjoy
//  @ File Name : StaticData.h
//  @ Date : 2017/9/28
//  @ Author :KrisChao
//
//


#if !defined(_STATICDATA_H)
#define _STATICDATA_H


class StaticData {
public:
	static StaticData * sharedStaticData();
	static void purge();
	int intValueForKey(const std::string &key);
	const char * stringValueFromKey(const std::string &key);
	float floatValueFromKey(const std::string &key);
	boolean booleanFromKey(const std::string &key);
	cocos2d::CCPoint pointFromKey(const std::string &key);
	cocos2d::CCRect rectFromKey(const std::string &key);
	cocos2d::CCSize sizeFormKey(const std::string &key);
protected:
	cocos2d::CCDictionary _dictionary;
	std::string _staticFileName;
	bool init();
private:
	StaticData();
	~StaticData();
};

#endif  //_STATICDATA_H
